version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(dependencies)"
    reviewers:
      - "albertoig"
    assignees:
      - "albertoig"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/actions"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(dependencies)"
    reviewers:
      - "albertoig"
    assignees:
      - "albertoig"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(dependencies)"
    reviewers:
      - "albertoig"
    assignees:
      - "albertoig"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(dependencies)"
    reviewers:
      - "albertoig"
    assignees:
      - "albertoig"
    labels:
      - "dependencies"
      - "npm"
