FROM ghcr.io/docked-titan-foundation/helmkit:v1.4.2

LABEL maintainer="HelmKit"
LABEL description="HelmKit Actions"

COPY scripts/action/entrypoint.sh /entrypoint.sh

# hadolint ignore=DL3002,DL3018
USER root

RUN chmod +x /entrypoint.sh

WORKDIR /workspace

ENTRYPOINT ["/entrypoint.sh"]

