name: "HelmKit Helm"
description: "Run Helm commands using HelmKit"
author: "HelmKit"
branding:
  icon: "box"
  color: "blue"

inputs:
  args:
    description: "Arguments passed to helm command"
    required: false
    default: ""

outputs:
  exit-code:
    description: "Exit code from helm command"
  output:
    description: "Output from helm command"

runs:
  using: "docker"
  image: "docker://ghcr.io/docked-titan-foundation/helmkit/actions:v1.3.0
  cmd: ["helm", "${{ inputs.args }}"]

credentials:
  username:
    description: "Username for image registry"
    required: false
  password:
    description: "Password/token for image registry"
    required: false