FROM ghcr.io/docked-titan-foundation/helmkit:latest

LABEL maintainer="HelmKit"
LABEL description="HelmKit Actions"

USER root

WORKDIR /workspace

# hadolint ignore=DL3002 - actions run as root intentionally
