name: Lint Dockerfile

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
  pull_request:
    branches:
      - main
    paths:
      - "Dockerfile"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Lint Dockerfile
        uses: hadolint/hadolint@v2.12.0
        with:
          dockerfile: Dockerfile
